config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'tasks', to: 'tasks#index'

  get 'tasks/new', to: 'tasks#new', as: 'new'
  post 'tasks', to: 'tasks#create'

  get 'tasks/:id', to: 'tasks#show', as: 'task'

  get 'tasks/:id/edit', to: 'tasks#edit', as: 'edit'
  patch 'tasks/:id', to: 'tasks#update'

  delete "tasks/:id", to: "tasks#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def edit
    @task = Task.find(params[:id])
  end

  def create
    title = params[:task][:title]
    details = params[:task][:details]
    @task = Task.new(title: title, details: details, completed: '0')
    @task.save
    redirect_to task_url(@task.id)
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to tasks_url
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(task) do |f|%>
  <%= f.label :title, 'Task name', class: "control-label" %><br>
  <%= f.text_field :title %><br>
  <%= f.label :details, 'Description', class: "control-label" %><br>
  <%= f.text_area :details %><br>
  <% unless task.new_record? %>
    <%= f.check_box :completed %>
  <% end %>
  <%= f.submit "Save / Update" %><br>
<% end %>

app/views/tasks/edit.html.erb
<h1>To-do</h1>
<div>
  <%= render 'form', task: @task %>
</div>

app/views/tasks/index.html.erb
<h1>To-do</h1>
<ul>
  <% @tasks.each do |task| %>
    <li>
      <%= check_box("tag", tag.id, {checked: task.completed?}) %>
      <%= link_to "#{task.title}", task_path(task.id) %>
      <%= link_to "X", task_path(task.id), method: :delete %>
    </li>
  <% end %>
</ul>

<%= link_to 'Add task', new_path %>

app/views/tasks/new.html.erb
<h1>To-do</h1>
<div>
  <%= render 'form', task: @task %>
</div>

app/views/tasks/show.html.erb
<h1>To-Do</h1>

<h2><%= @task.title %></h2>

<p><%= @task.details %></p>
<%= link_to 'Edit', edit_path(@task.id)%>
<%= link_to 'Back to list', tasks_path %>